### ISSUE TITLE
[ ] の重複

### ISSUE THREAD

**Issue by 3to5thpower** [RitsCompilerConstruction/Report#2]
第５ページ下部〜第６ページ頭にかけての一文の中で[ ]が重複しており、どちらかはnilだと考えられます

**Comment by 0918nobita** [comment]
[https://github.com/RitsCompilerConstruction/Report/commit/3533043ef865182cf5359a3e9bd8ca7f81f899ad](https://github.com/RitsCompilerConstruction/Report/commit/3533043ef865182cf5359a3e9bd8ca7f81f899ad) 修正しました
